name: SQL for GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1.5.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbDefinition/createTables.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbDefinition/addConstraints.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Insert/sqlInsertion.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Procedures/addStudentProcedure.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/acceptedStudentsView.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/fundedInstitutions.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/pedingInstitutions.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/pendingStudentsView.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/rejectedInstitutions.sql"
      - uses: azure/sql-action@v2
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: "./src/db/dbManipulation/Views/rejectedStudentsView.sql"

      # Azure logout
      - name: logout
        run: |
          az logout
